### ISSUE TITLE
Cloudinit format and reading file from current working directory - C#

### ISSUE THREAD

**Issue by naveenkumarsp** [pulumi/pulumi-cloudinit#14]
This is more of a question than bug. I am noob in Pulumi. I have been trying to deploy the VMSS with cloud-init script to format mount the filesystem.

I had used same setup in Terraform and it worked for me. Seems i am missing some formatting due to which the cloud-init is not working. Also i am not sure how to troubleshoot this.

Any help to course correct it will be appreciated. 

Here is the snippet of pulumi script

```
        var conf = new Pulumi.CloudInit.Config("CloudConfig", new Pulumi.CloudInit.ConfigArgs
          {
              Gzip = true,
              Base64Encode = true,
              Parts =
              {
                  new Pulumi.CloudInit.Inputs.ConfigPartArgs()
                  {
                      Content = "baz",
                      ContentType = "text/cloud-config",
                      Filename = "cloud-init.tpl",
                  }
              }
          });


        var main = new Azure.Compute.LinuxVirtualMachineScaleSet(vmssName, new Azure.Compute.LinuxVirtualMachineScaleSetArgs
        {
            ResourceGroupName = core_rg.Apply(core_rg => core_rg.Name),
            Location = core_rg.Apply(core_rg => core_rg.Location),
            Sku = vmSize,
            Instances = instanceCount,
            AdminUsername = adminUsername,
            AdminPassword = adminPassword,
            DisablePasswordAuthentication = false,
            CustomData = conf.Rendered,
            SourceImageReference = new Azure.Compute.Inputs.LinuxVirtualMachineScaleSetSourceImageReferenceArgs

```

Cloud-init script

```
#cloud-config
disk_setup:
  /dev/disk/azure/scsi1/lun10:
    table_type: gpt
    layout: true
    overwrite: false

fs_setup:
  - device: /dev/disk/azure/scsi1/lun10
    partition: 1
    filesystem: ext4

mounts:
  - [
      "/dev/disk/azure/scsi1/lun10-part1",
      "/datadrive",
      auto,
      "defaults,noexec,nofail",
    ]
```

**Comment by lukehoban** [comment]
@naveenkumarsp What is the error you are ultimately seeing here?  (That is - what is actually not working as expected here?)

**Comment by naveenkumarsp** [comment]
@lukehoban  - When deployed, i am not able to see the disk being formatted and mounted as /datadrive on the scaleset VMs. 
I looked up the cloud-init logs and i couldn't find any output either as well the i couldnt find the file /var/lib/cloud-init.

May be i am missing something.  Will the file be picked up automatically from PWD or does the content had to be loaded to a variable?

**Comment by leezen** [comment]
@naveenkumarsp Could you please try with `getConfig` (https://www.pulumi.com/docs/reference/pkg/cloudinit/getconfig/) instead of the `Config` resource? The `Config` resource is actually just a wrapper around that function in this provider and I wonder if there's a bug in how that wrapping takes place.

**Comment by naveenkumarsp** [comment]
@leezen - i have tried using getconfig but no luck. the cloud config which I used is as follows

```
var CloudInitConfig= Output.Create(CloudInit.GetConfig.InvokeAsync(new CloudInit.GetConfigArgs
        {
            Base64Encode = true,
            Gzip = true,
            Parts = 
            {
                new CloudInit.Inputs.GetConfigPartArgs
                {
                    Content = "baz",
                    ContentType = "text/cloud-config",
                    Filename = "cloud-init.tpl",
                },
            },
        }));
```
### VMSS where cloudconfig was referenced as follows.
```
                OsProfile = new AzureNative.Compute.Inputs.VirtualMachineScaleSetOSProfileArgs
                {
                    AdminPassword = adminPassword,
                    AdminUsername = adminUsername,
                    ComputerNamePrefix = vmssName,
                    CustomData = CloudInitConfig.Apply(CloudInitConfig => CloudInitConfig.Rendered),
                },
                StorageProfile = new AzureNative.Compute.Inputs.VirtualMachineScaleSetStorageProfileArgs
 
```

**Comment by leezen** [comment]
Have you verified that the rendered script is correct via the Azure CLI or Portal?

**Comment by guineveresaenger** [comment]
Closing this issue as stale. As always, re-open if this persists.
