### ISSUE TITLE
Verification warning: deprecated resource?

### ISSUE THREAD

**Issue by antifuchs** [pulumi/pulumi-cloudinit#23]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

We're using pulumi-cloudinit to provide launch configs to our EC2 instances, and are getting this error:

```
Diagnostics:
  cloudinit:index:Config (my-launch-config):
    warning: urn:pulumi:dev::pulumi-cloudinit::cloudinit:index/config:Config::my-launch-config verification warning: Deprecated Resource
```

...but it's not clear what resource is being deprecated. Is this provider still supported?

### Steps to reproduce

Pull in `pulumi-cloudinit==1.3.0` and use the following main.py:

```py
"""An AWS Python Pulumi program"""

import pulumi
import json
from textwrap import dedent
import pulumi_cloudinit as cloudinit

launch_config_userdata = {
    "packages": ["sl"],
}

cloudinit.Config(
    "my-launch-config",
    base64_encode=True,
    gzip=False,
    parts=[
        cloudinit.ConfigPartArgs(
            content_type="text/cloud-config",
            content=dedent(
                f"""\
            #cloud-config
            {json.dumps(launch_config_userdata)}
            """
            ),
        ),
    ],
)
```

Then `pulumi preview`.

Expected: No warnings.
Actual: 
```
Diagnostics:
  cloudinit:index:Config (my-launch-config):
    warning: urn:pulumi:dev::pulumi-cloudinit::cloudinit:index/config:Config::my-launch-config verification warning: Deprecated Resource
```

**Comment by pierskarsenbarg** [comment]
This resource was deprecated upstream so you should use the `get_config` method instead (there's an [example in the registry](https://www.pulumi.com/registry/packages/cloudinit/api-docs/getconfig/#example-usage)).

**Comment by rafalkrupinski** [comment]
Actually the registry show example using the deprecated cloudinit.Config: https://www.pulumi.com/registry/packages/cloudinit/
